### ISSUE TITLE
Warning in compilation

### ISSUE THREAD

**Issue by OzOns** [adafruit/Ethernet2#10]
Hi everybody,

Thanks a lot for the good job, making Wiz5500 available for us

When I compile I have some warnings (high level of verbose). I wonder if it is important or not.

Thanks again for the job.

Philippe

like: 
C:\Program Files (x86)\Arduino\libraries\Ethernet2\src\Dns.cpp:313:58: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

     for (uint16_t i =0; i < htons(*((uint16_t*)&header[4])); i++)

                                                          ^
C:\Program Files (x86)\Arduino\libraries\Ethernet2\src\utility/util.h:5:22: note: in definition of macro 'htons'

                    ((x)>> 8 & 0x00FF) )

                      ^

C:\Program Files (x86)\Arduino\libraries\Ethernet2\src\utility\socket.cpp:322:19: warning: unused parameter 's' [-Wunused-parameter]

 void flush(SOCKET s) {

**Comment by ladyada** [comment]
This library is no longer going to be used, since the official Arduino library has been updated and works great https://github.com/arduino-libraries/Ethernet
