### ISSUE TITLE
WIZ550io & dhcp

### ISSUE THREAD

**Issue by jenschr** [adafruit/Ethernet2#12]
I'm using a Feather WICED with a WIZ550io module. If I don't call:

`Ethernet.init( PA4 );`

the WIZ550io module will never start. I have confirmed that SS is correctly set to PA4 (in feather.h), so it's not setting the pin itself that makes this work, but I presume that the init method also calls something that makes the Wiznet module work?

To reproduce, connect a WIZ550io module and use the "webclient" example for Ethernet2. This will just hang and never init the module:

```
  if (Ethernet.begin(mac) == 0) {
    Serial.println("Failed to configure Ethernet using DHCP");
    // no point in carrying on, so do nothing forevermore:
    // try to congifure using IP address instead of DHCP:
    Ethernet.begin(mac, ip);
  }
```

This will work every time and init with DHCP address within a second:

```
  Ethernet.init( PA4 );
  if (Ethernet.begin(mac) == 0) {
    Serial.println("Failed to configure Ethernet using DHCP");
    // no point in carrying on, so do nothing forevermore:
    // try to congifure using IP address instead of DHCP:
    Ethernet.begin(mac, ip);
  }
```

PS: you might want to correct the "congifure"-typo in the comments also ;-)

**Comment by ladyada** [comment]
This library is no longer going to be used, since the official Arduino library has been updated and works great https://github.com/arduino-libraries/Ethernet
