### ISSUE TITLE
Leonardo break when trying to initialize Ethernet object from class

### ISSUE THREAD

**Issue by elhayrobotican** [adafruit/Ethernet2#15]
Hi, 

I created a project with some class (header and cpp files).
When I tried invoking `Ethernet.begin(mac_addr);` from the constructor of the class, Leonardo breaks after upload, and I am not able to upload anymore (pc can't detect Leonardo's usb port).
When invoking `Ethernet.begin(mac_addr);` from within setup() function in the ino file, the issue doesn't exist.

**Comment by ladyada** [comment]
This library is no longer going to be used, since the official Arduino library has been updated and works great https://github.com/arduino-libraries/Ethernet
