### ISSUE TITLE
AdvancedChatServer example is wrong

### ISSUE THREAD

**Issue by bhelterline** [adafruit/Ethernet2#16]
The AdvancedChatServer example has this defect:

```
void setup() {
  // initialize the ethernet device
  Ethernet.begin(mac, ip, gateway, subnet);

```
There should be a dns_server in there
(look at the AdvancedChatServer example for ethernet vs. ethernet2)

`  void begin(uint8_t *mac_address, IPAddress local_ip, IPAddress dns_server, IPAddress gateway, IPAddress subnet);

`

**Comment by ladyada** [comment]
This library is no longer going to be used, since the official Arduino library has been updated and works great https://github.com/arduino-libraries/Ethernet
