### ISSUE TITLE
Null termination

### ISSUE THREAD

**Issue by ldaman** [adafruit/Ethernet2#18]
Hello

Here is the problem I noticed.
I am using Ethernet2 library with Ethernet shield and Arduino Uno.
I receive messages over UDP from a "box" that I have no control over.  
The issue I am facing is when I receive the data 16 bytes, it is being truncated when encounters a null termination.

Example.
Box sends  (data captured on UDP tool)
hex code.   62 00 00 00 00 D2 00 00 00 00 00 00 62 00 00 00 (in Decimal code:  98 0 0 0 0 210 0 0 0 0 0 0 98 0 0 0)

On Arduino side, I receive the 62, then nothing after that.

One thing to note is that when I did my own testing and sending data from my pc. it is consistent, when I send the exact data above, it stop. If replace the 00 with comma or 01, I receive the entire data packet.. 

I am using this something similar to your example.... 
#include <Ethernet2.h>
....
Udp.read(udpRawData, 40);
... iterating through the udpRawData in for loop.

Question
Is the library expecting null terminated string? if so how to go around this.  I know I will be receiving fixed length of bytes. Is there a way to bypass the null terminated check?

**Comment by ladyada** [comment]
This library is no longer going to be used, since the official Arduino library has been updated and works great https://github.com/arduino-libraries/Ethernet
