### ISSUE TITLE
v1.0.4 Twitter.c/.h won't compile in Atmel Studio 7, M0 PRO board

### ISSUE THREAD

**Issue by olemr** [adafruit/Ethernet2#23]
Since I don't even have a Twitter account, I deleted the two files and it compiles and ran fine on the M0 PRO with the W5500 Ethernet Shield 2.
Thanks for your great work!

**Comment by ladyada** [comment]
This library is no longer going to be used, since the official Arduino library has been updated and works great https://github.com/arduino-libraries/Ethernet
