### ISSUE TITLE
IP address for Ethernet shield

### ISSUE THREAD

**Issue by mhmdajami** [adafruit/Ethernet2#27]
I forget the IP address of Ethernet shield. How can I know it?

I open network and sharing center there is a new device connect but its didn't sent or receive.
Then I search on cmd config/all there is no new device that i can ping on to get IP address.
I try to connect it to switch to see the plugged in device there is no thing it didn't appear.
Also i try to connect it to router and follow tutorial and there is no result. is there is any certain protocol?

**Comment by ladyada** [comment]
https://github.com/adafruit/Ethernet2/blob/master/examples/WebClientRepeating/WebClientRepeating.ino#L63
