### ISSUE TITLE
suboptimal SPI usage in write function on Nucleo platform

### ISSUE THREAD

**Issue by d21d3q** [adafruit/Ethernet2#28]
- Arduino board:  **Nucleo**

- Arduino IDE version:  **1.8.5**

I am working on with Nucleo board and since stm32's SPI setup is more complex (than setting couple of registers) calling `SPI.beginTransaction` causes long delays in communication.
Transfer requires at least one call to `beginTransaction` so theoretically it should be enough.

How does it look like in practice? After uploading `WebServer` example and fetching data in browser, developer tools are showing 600-700 ms of waiting time.
I've plugged in logic analyzer and  used one pin for time tracing.

```c++
uint8_t W5500Class::write(uint16_t _addr, uint8_t _cb, uint8_t _data)
{
    digitalWrite(D8, HIGH);
    SPI.beginTransaction(wiznet_SPI_settings);
    setSS();  
    SPI.transfer(_addr >> 8);
    SPI.transfer(_addr & 0xFF);
    SPI.transfer(_cb);
    SPI.transfer(_data);
    resetSS();
    SPI.endTransaction();

    digitalWrite(D8, LOW);
    return 1;
}

uint16_t W5500Class::write(uint16_t _addr, uint8_t _cb, const uint8_t *_buf, uint16_t _len)
{
    digitalWrite(D8, HIGH);
    SPI.beginTransaction(wiznet_SPI_settings);
    setSS();
    SPI.transfer(_addr >> 8);
    SPI.transfer(_addr & 0xFF);
    SPI.transfer(_cb);
    for (uint16_t i=0; i<_len; i++){
        SPI.transfer(_buf[i]);
    }
    resetSS();
    SPI.endTransaction();

    digitalWrite(D8, LOW);
    return _len;
}
```

Here is result:
![2018-05-29-001223_1567x529_scrot](https://user-images.githubusercontent.com/490844/40630989-09d3e194-62d8-11e8-8705-eb962962e076.png)
By checking slopes of D8 and CS you can see that `beginTransaction` takes about 45 µs and takes longer than reset of function...
After commenting out `beginTransaction` and `endTransaction` I managed to halve the time needed for page load (around 260ms), and timing looks as follow:
![2018-05-29-001619_1459x374_scrot](https://user-images.githubusercontent.com/490844/40631053-caea1c5e-62d8-11e8-805d-e9607e57ccdb.png)

I checked the same on Arduino Nano and there were no observable time differences w/ w/o `beginTransaction` (around 230 ms):
![2018-05-29-010549_763x352_scrot](https://user-images.githubusercontent.com/490844/40631387-8a6cca74-62dc-11e8-9ba6-10079f0cbd60.png)

If one is curious: [this](https://github.com/arduino/ArduinoCore-avr/blob/3f63f2975e7183c3254b6794bfcc8f19ca0301c9/libraries/SPI/src/SPI.h#L203) is SPI initialization on avr (yes, those two lines), and for Nucleo [here](https://github.com/stm32duino/Arduino_Core_STM32/blob/9bb2a170a4403f27a8e01f84623754081ebb7121/libraries/SPI/src/SPI.cpp#L126) is call to `spi_init` which looks like [this](https://github.com/stm32duino/Arduino_Core_STM32/blob/4eb33909fc48d9d9a1f192af78a4cedc64626727/cores/arduino/stm32/spi_com.c#L188) on stm32duino...

**Comment by ladyada** [comment]
This library is no longer going to be used, since the official Arduino library has been updated and works great https://github.com/arduino-libraries/Ethernet
