### ISSUE TITLE
Memory leak, despite fixes

### ISSUE THREAD

**Issue by LozK** [adafruit/Ethernet2#30]
- Arduino board: Own PCB with ATmega1284P-PU and WIZ850io (WIZnet Networking Module with W5500 and MAG Jack)
- Arduino IDE version 1.8.5

I have been using this Ethernet2 library for sending data from a datalogging board I designed. I have managed to send data using the WIZ850io/W5500 and library, repeatedly sending data to a server via POST requests without issue.

I have run into problems, though, when using repeated calls to Ethernet.begin([MacAddress]), which I have to do as I need to de-power the WIZ850io/W5500. I need to do that as the whole project is running off battery power (data is being sent out over a modem using cellular/mobile data) and the WIZ850io uses quite a bit of power.

Each time Ethernet.begin([MacAddress]) is re-called (after the WIZ850io is de-powered, the ATmega1284 sleeps, then the WIZ850io is powered up again), an extra 26 bytes of RAM is lost, never to return. Though the ATmega1284 has more memory than smaller ICs, this runs out after 500 or so calls to Ethernet.begin([MacAddress]).

While data are being sent fine and reliably, the memory leak causes the processor to seize up after a number of Ethernet restarts.

I found mention of a memory leak fix on a different version of this library here:

https://github.com/arduino-org/Arduino/pull/72/files?diff=unified

It seems that the setting of `DhcpClass* _dhcp = NULL;` mentioned there, in file Ethernet2.h, is done in a similar, but different way in this library, and the check for `_dhcp != NULL` and subsequent `delete _dhcp;` before the `_dhcp = new DhcpClass()` line, in Ethernet2.cpp, is done in the same way in this library.

Yet, I still seem to get a memory leak, so I’m wondering if there is anywhere else that memory needs to be freed, or if there is another way to structure the code so that the _dhcp = new DhcpClass() is done only once, but the rest of the Ethernet.begin([MacAddress]) function can be called to renew/refresh the connection to the W5500 IC?

**Comment by ladyada** [comment]
This library is no longer going to be used, since the official Arduino library has been updated and works great https://github.com/arduino-libraries/Ethernet
