### ISSUE TITLE
ESP32+Ethernet2.h+Encryption+PubSubClient

### ISSUE THREAD

**Issue by davidrs16** [adafruit/Ethernet2#34]
Hi all,

I have an Adafruit Feather ESP32 and FeatherWings ethernet module and I am having issues to encrypt the comunicaciont with MQTT Broker. 
In this case I have tried the following libraries with out success:
1.- Ethernet2.h+WiFiClientSecure+PubSubClient.h
2.- EHT.h+WiFiClientSecure.h+PubSubClient.h

In the past I use ESP32+LAN8720 with the libraries EHT.h+WiFiClientSecure.h+PubSubClient.h and work as expected.

Do you know if there is any other posibility to implement Encryption in ESP32 and MQTT Broker?

**Comment by ladyada** [comment]
This library is no longer going to be used, since the official Arduino library has been updated and works great https://github.com/arduino-libraries/Ethernet
