### ISSUE TITLE
Could you add this library to Arduino IDE's library manager?

### ISSUE THREAD

**Issue by q2dg** [adafruit/Ethernet2#4]
Thanks!

**Comment by njh** [comment]
I created a request to add the `Ethernet 2` library to the Library Manager.

But @per1234 responded saying:
"Adafruit would need to make a release or tag for that library to be picked up by Library Manager."

**Comment by toddtreece** [comment]
@njh & @q2dg release v1.0 added

**Comment by q2dg** [comment]
Thanks!
If you don't mind, i'll close the issue
