### ISSUE TITLE
Update description to make it clear it is for W5500 / Ethernet 2 shield

### ISSUE THREAD

**Issue by njh** [adafruit/Ethernet2#6]
The description is currently the same as the 'v1' shield / W5100.
- http://www.arduinolibraries.info/libraries/ethernet
- http://www.arduinolibraries.info/libraries/ethernet2

I can submit a PR if that is helpful.

**Comment by toddtreece** [comment]
thanks, @njh. pull requests are always welcome!

**Comment by njh** [comment]
Sorry, I completely forgot about this; just raised a PR with some enhancements:
https://github.com/adafruit/Ethernet2/pull/9
