### ISSUE TITLE
SPI settings in w5500.cpp

### ISSUE THREAD

**Issue by SurferTim** [adafruit/Ethernet2#7]
The default SPI settings in /utilityw5500.cpp is incorrect. The speed is set to 800000 (.8MHz). It should be 4000000(4MHz) or 8000000(8MHz).
`SPISettings wiznet_SPI_settings(800000, MSBFIRST, SPI_MODE0);`

**Comment by ladyada** [comment]
oh yea! ok!

**Comment by srolf** [comment]
Is there a chance to add support for 42MHz SPI speed like the [Due seems to support](https://github.com/arduino/Arduino/issues/5870)?

```
#ifdef W5500_DUE_42MHZ_SPI // Arduino Due specific
SPISettings wiznet_SPI_settings(42000000, MSBFIRST, SPI_MODE0);
#else
SPISettings wiznet_SPI_settings(8000000, MSBFIRST, SPI_MODE0);
#endif
```
